language: node_js

os: linux

dist: bionic

node_js:
  - "stable"

cache:
  directories:
  - node_modules

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: ThaminduR/idb-backend
  bucket: idb-bucket
  region: ap-southeast-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: idb-bucket
  key: buildb.zip
  bundle_type: zip
  application: CodeDeployIDB-B
  deployment_group: CodeDeployIDB-B-Group
  region: ap-southeast-1
  on: *2

script:
  - zip -r buildb *
  - mkdir -p dpl_cd_upload
  - mv buildb.zip dpl_cd_upload/buildb.zip