language: node_js

os: linux

dist: bionic

node_js:
  - "stable"

cache:
  directories:
  - node_modules

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: ThaminduR/idb-backend
  bucket: idb-code-bucket
  region: ap-south-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: idb-code-bucket
  key: build-backend.zip
  bundle_type: zip
  application: CodeDeploy-Backend
  deployment_group: CodeDeploy-Backend-Group
  region: ap-south-1
  on: *2

script:
  - zip -r build-backend *
  - mkdir -p dpl_cd_upload
  - mv build-backend.zip dpl_cd_upload/build-backend.zip